#!/usr/bin/env bash
# scripts/install/tmux-config.sh - tmux.conf setup, platform config, kill stale server, update ~/.tmux.conf

setup_tmux_config() {
  # === 6. install tmux.conf ===
  mkdir -p "$BATIPANEL_HOME/config"
  cp "$SCRIPT_DIR/config/tmux.conf" "$BATIPANEL_HOME/config/tmux.conf"
  cp "$SCRIPT_DIR/config/tmux-powerline.conf" "$BATIPANEL_HOME/config/tmux-powerline.conf" 2>/dev/null || true

  # generate platform-specific config (no if-shell needed — detected at install time)
  _PLATFORM_CONF="$BATIPANEL_HOME/config/tmux-platform.conf"
  {
    echo "# batipanel platform config (auto-generated by install.sh)"
    echo ""

    # clipboard
    case "$OS" in
      Darwin)
        echo "# macOS clipboard"
        echo "bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'"
        ;;
      *)
        if grep -qi microsoft /proc/version 2>/dev/null; then
          # WSL: always use clip.exe (xclip needs X server which WSL lacks)
          echo "# WSL clipboard"
          echo "bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'clip.exe'"
        elif command -v xclip &>/dev/null; then
          echo "# Linux clipboard (xclip)"
          echo "bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard'"
        fi
        ;;
    esac

    # default shell
    local_shell="${SHELL:-}"
    if [ -n "$local_shell" ] && [ -x "$local_shell" ]; then
      echo ""
      echo "# user shell"
      echo "set -g default-shell \"$local_shell\""
    fi

    echo ""
    echo "# theme overlay (generated by 'b theme')"
    echo "source-file $BATIPANEL_HOME/config/theme.conf"
  } > "$_PLATFORM_CONF"
  echo "  Generated platform config"

  # guarantee theme.conf exists (empty = no theme = default tmux colors)
  if [ ! -f "$BATIPANEL_HOME/config/theme.conf" ]; then
    echo "# batipanel theme (auto-generated, use 'b theme' to change)" > "$BATIPANEL_HOME/config/theme.conf"
  fi

  # kill stale tmux server so new config takes effect
  # warn if there are active sessions before killing
  if tmux list-sessions 2>/dev/null | grep -q .; then
    echo "  WARNING: killing tmux server with active sessions to apply new config"
  fi
  tmux kill-server 2>/dev/null || true
  # clean stale socket (dead server leaves socket behind, blocks new sessions)
  rm -rf "/tmp/tmux-$(id -u)/" "/private/tmp/tmux-$(id -u)/" 2>/dev/null || true

  # clean ~/.tmux.conf (remove ALL old batipanel lines, then add fresh)
  BATIPANEL_SOURCE_LINE="source-file $BATIPANEL_HOME/config/tmux.conf"
  if [ -f ~/.tmux.conf ]; then
    sed_i '/batipanel/d' ~/.tmux.conf 2>/dev/null || true
  fi
  {
    echo ""
    echo "# batipanel"
    echo "$BATIPANEL_SOURCE_LINE"
  } >> ~/.tmux.conf
  echo "  Configured ~/.tmux.conf"
}
